[tool.poetry]
name = "dz-pw-4"
version = "0.1.0"
description = ""
authors = ["Andrey <KorenbAS78@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

